sudo: false
language: node_js
node_js:
- '12'
branches:
  only:
  - master
script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: make release
  on:
    branch: master
    node_js: 12
- provider: script
  skip_cleanup: true
  script: bash ./.makefiles/publish.sh
  on:
    branch: master
    node_js: 12
env:
  global:
  - ALIYUN_ENDPOINT=http://39.98.93.191/admin
  - ALIYUN_ACCESS_KEY=z1aWXyf27QaUtAAT6wv4t5sL4visgBhRBPb
  - AWS_ENDPOINT=http://54.213.55.12/admin
  - AWS_ACCESS_KEY=z1W9k2T7XTddPMtArMs7gs6pJYvsN63dggE
  - secure: L6qmnGYssIUdRLD/cr5jVSKh6YFCJYQrKyBCLIQ/rFUVUoLZ3laHWM+z/agR8o+5/Wp5D+E7da89bWr/AzMsTgdIUH6/jFQ0ngpy6wHfS4enswYIZi0hINDXeCz1UPlbqQnjoRcqQVrk14L3E2KC2zO5lTI8B6Or3ND17IeW0CEOP8hhfHIGV5rjJE62w1VGjSXu0PBUrZamDB2HFXE4mNBtYc5ceoNyGd64onJo4sKku5sya6BaArJLymcAs5z22mgm/qhbDp5AUYT4f9LuuO0+hPV0q8L1J/fsQ9xgTfJfjxGj+IO+/IyXmud7rhpNiCMWBMeKrbHtWW8lv5WlEBMzkB07/wc1U1ou5Pn5IdoQrb7ojqlCQVoHG+4DbHLnjkW5DBrvC3S8msSTYhPoi5OfGFe5c88VtwqIrkkoDtw1DBM9aloUyHyhMXepguJ4i3FKFD0SqU+GIgk8VwkBw2AZYOCwff9ovVv5NLmx/Wkjr0JNNdz4ygJN7XXIjDzMP/tFgHGIteIfFmS2wleX4odBotDTQbkQhRw+WbKyw4ThqPFJNGwmOZ5n/ZbHTF7whZacSELeByen6CZoyqNX4tx40uBTCet+OlDC2LAmHj2mQveiQURLHV0HVMDkGHvkryjRruYOsH6iVa7o38DQA1BfOUyQ1kiGd8Oxv3qFd+I=
  - secure: s5YqvjeRmG9W17xyYuE4oQZ4qgkPUhdYvbLpw1ghpj94svjI8faHGpGnCuGj/Uzv3jIHxaDwbyQszVL/IUGarbsO6m0hfOP06mAnakD/rr/pP9y/sWXowtbEF0feAKYfQFNnxHXH3N6zU3tkxO04jO0VrBci16jaViBn4yUq/XK3bEm1RqwItze8XZpszDU/geHLitT7h1GpnhbCOFrdo3RhCYs2VgbT4VfyDEyJ8ntsDPPhajsXugP1VpBOt1TbVA8bTvykgQI8c7RQWFyelioUogkVXlVW9cFjHFyrtPVggtugv1INTa7Pd6Y0ZXLTY9g/UHAObMnbXN5X6UFBIKkeE4cWTrd3UhhvGAqGkbqe5gijpV17iYYzTK7CZyMbdVSNcjAGcM0XYSl18tMgufBRThbeP0lw1aerF/hkfB/0Dn9sxXh+Ii6ZCL53yrUVObJU9jbCiLOys5g7KrPY/VeH0otyInLJEV+HvFJidAWE14mocoYFEenis07FcZLW3uy8Z6swxjYzQp2EUl2rQ4i+MM4w8iYZGIPUyKiLICQyn7kYlBGYFAVfSo+UOqL1Yj5hdNsWNFTF742XbvKoggeO7xBl51oZFW9uWE2uTPjTiM2p6P4mGg1ojRNt4qthZTORlkINNMEd7k6VUSPAmRJu80pIc/vVLg4iFp1Et74=
  - secure: VZnCOE+H7rllFoRDA6YtNipAHam5qYhlUUbg+2TGS5XIMoPLodbSFK3El0GDlTBAAZYLnzSEVhgQhm7jyHzCDZ9f0hlm2qhFpDZj/UxCXSdCAW/cajBjiNOVh0TKCC6pyW0/xZqLyPTnHvLilgbQmckO3Ow848xRT0fW92ZdhlzwvHNivBLVGoz6376p0SIbxg9SObm9lCDOahEsbouTILIs8gmubg/lbgMNdzPR8Q5TTlJrWpsZ4OSLpoXRXBY/z+vB8k2Fd/emxUmUSOqkgc+CpsCTwDVsvnYEeQiL06gfORwXkd07MFlzqSVsrj+nyJK1j3TowDP7e30n2+748Ts9PGBfcklHvY6Vt7K8TU8LFkvMQvv9KghLRFZ3Hreou8OT1Ld/8euDgUg/AMH7AvMXEKbrg6EZ8Ga6epdD88kk8zgaEi6QLluXA5ZSYCpZFdpLlI4tO4dXMJWDo8+Yl0zDSlAqwD07KXlF7GWtFA4M13qXXqB77xqkuIw+5nvtXnWoQ3EqFEBSYNS+EBD+9SimOkxmf+6zgpLnD96XCBkmBvYEGkOgbPgGYJf7bdv/z2ZxHCbdtN2CfDpDkTuGppGESi+aIaOCO/yzJiPJSjlpOHzLfYV9ghKiBC2FUibBBMCQWapqwNT1KFzHS8oJGsHQL/9FXbcl1PC0gPRpYVU=
