sudo: false
language: node_js
node_js:
- '12'
branches:
  only:
  - master
script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: make release
  on:
    branch: master
    node_js: 12
- provider: script
  skip_cleanup: true
  script: bash ./.makefiles/publish.sh
  on:
    branch: master
    node_js: 12
env:
  global:
  - ALIYUN_ENDPOINT=http://39.98.93.191/admin
  - ALIYUN_ACCESS_KEY=z1aWXyf27QaUtAAT6wv4t5sL4visgBhRBPb
  - AWS_ENDPOINT=http://54.213.55.12/admin
  - AWS_ACCESS_KEY=z1W9k2T7XTddPMtArMs7gs6pJYvsN63dggE
  - secure: tqqx6Uv1BC2lJM1HZZ7w9mxjlq+k44cpmQMDwLlpXXhXIiw32alqN+3yept+XR+0xbuDieV4VEVt2N8B8MTr/OdAuARa19YJ7zog8QAW9mIJ6hR/RA2ZARsKdRtKXnMOCSTahs8AT7udhxi5FIOc+75bSDoDUYwF/ToLGsfU+KRcBGODZtNuae0aIw2dyXbVEHz9FtknZpVuJMATSjOYFDlJrjulmBFGP+gEdK6Ddy+G+yfH0J2I3VaXK8769iOwAujxfW2McHjEznPpMX6xzj7KduQTCXo7PzB8IkqZ2gJ1s8/1UV2+82Tv22htCqAS6Yoi3k2n2tSSF6JRJNEMVpX9JIwqvgsRerUcWQYINuvV1ulWa99JOCvSio2CV3EJg5ZItjxqsJtn5YeEkEHMGCI26sVOYX6EB6anFg5z95Br8Y37iip8SRECz8ee5qZa88oyjBNUttTWm1TTuHGC70+M2l+6uyf8cGp1CrFV+zSrYIuDrVPWY3SUmX6Z+ggmH6SE9JohzmXYPyGWb9Bs0RFH4j5Eqrig8OvLOEIQn9XQkNciJ1h0Md2RGnEpP8Nvm/JUCubnURizmZAd7Osto/QQ3f7lDaseSO8eJdH1eSCAdaJXqd9RPY4JQrTT6qKjHpRAXJusDZhKakJDqkL/D2zNMAzlm5FeoMnXpU4GuAw=
  - secure: DS3dcyFntTOVNU4EwBLk1n286c0S8H83cY2qN+Rbh7QFyEkdOFLgBqnAYbOWmYpOnOaN0f8IJw70RbooQuWNzPR1NrRJBUGtFSLJBQ5SWWtru5f/iPKT3YctSiBLBUW28OQ6AZy7AWNl/YtaHE43/na3RUJpWlXhReqw4mvzY25gqkmBVvkAqnttuwBy5m2TyTayInGK0XjHQcxqN8QEZGvHIR6DnMYX+3d82O0hcGNqmUCV+gPMkeFALTHuLiS41WPCZ7Ii6sI5XQOmKn/DyTio5+owuvEYqCDglRvep2Tzw9MzFL+yxpGJ6cI4/vG9IwNfyuZ6UKGXHAqQAVjmJVRill0cv81KvQqaLXE2wWCjZrtVhp65UVj6UIIcGR36WQSnR09py9jo52wB/iBTsvZLyaplmqEsvbDFYvswx5Y9ktQDc5vDd72UtXVjROcU8/i0mKCv07PQn0FswkuDXprQtuAT6ou+ECei50QAzcJgoQ8vA64jlSEc7avn4GNrpCDvFv2OVEU/o9LyriVd1YCtV7RoFvhY6TaAqTU7xxQo2mP03iApr7VZF8QTWW0eX+gx9C5Ic+hLIe3HWnDSGeIyshS/u4zbeUEe5CxTlIHL8NOdZa1RlMBhMiqO06HxBy+KL7pzoP38rTm/UwNoeIp0RBIt6XmTYj3v1ihYGXU=
  # ALIYUN_ACCESS_SECRET
  - secure: L0Ag6b/bTcz1OfzWpt4LlTBc/HrulZWLj/2HXyMKhacxGNprvvjutAr9uyo0SDRa2mhvMlYvZ9HlYunMDyQYGs5CnFyy3O/b4S2mHb5o3GI31FGg/B5oB7Zio+dp9NJfd64aAr3mzRGps2KwuoMIFHIaj8AXyZKPY+iR8nzy4n3+O/aGNyMLO/Lxcy1ibru1GxVmd+wnLD4yGJvFbnSb9ltob4AoZJAVeJCak2S8AvDkqYpqsfMhqc7CIGrVNDq3Tml74jjVsm1Wntzfu45rY+3Zg8hc+HZjIrQjP6/14iNmzbXoO9XNLdGKlRyPoLDajLo9kchJlJTSwoFUytHjFFoUfLhvZiUQH55QQZZ/k3QY0K+b+1x8XGiNOCLzimUi8rYPh+VtQLRAOCmtC7nZtOfR//mp7oNq4ij64gtKn4xifceseRvuuESiylaRcU90OrJd5zVQpy0jR36qewhL3TkAz3O1tE8UeX4u0IbOhSXUFCXgKvWWRGUJkhezLHx7mgv55LYyXAe6rt91PiJdpNn387EDDwlvs8Zbxzt8RaR4CdEnHzlG8yktOcmwAUxMEcbPUAPIK4X18RQdPWAI+S1w04Bk5oCEoP9CYPSjgPLvqbFTborD+4cZ/DSKNbuUWw9mhPSDUBXqWgY5BArXca6GdPgL6qCB6rddRX9WSFE=
  # AWS_ACCESS_SECRET
  - secure: hQVhzSZ1KQWHETpkmIg3EAQ7nG5bRuYc2IbS6w4LWTLPiec/DGMtDFEPaDcgOcH3kdsdnMLnSt/dIMa6T8/V3p7e5dg4FCGFzSAygr8OoHz70HgM7rEr1I9CqyHDn8nd+7nm0rZvXg+E+EgqyWt1888noUbzj32mxh2c4MltvseH0tGSrGiTBaOXEQ/zJtby9nCfRWpGqLiXgOjoj4JST4NK5mXtJbbFbtHCTDxpRavHcJLIENrmXvHJN4YSbyeksAZb84sxgfZdGQpGnehBGk+mxW68ZRoVoRig02qd/mD80UmWB8mHMe9NBlNizQbsbwp+OkbR/d2ZXDhgeCmYqNISKdxT2hB3VBkG1c9Nr7qH3rddIUwLvk4+O+LhoT7yMai8q/+6dYyrwg8ziV2OvGIfd7WnjlS3gfDofkIiM7+A+K5R/EnkyNudxWuAr5A/qdK2YISp11YpgU5v9Tb7gcgBBahU6pzfWd6kMFdc1WNhZ9cXlyJAO1q9mrZXVJ0HeUqT/zLS5qDZLbLqBQvJcPfF2ueb6u+TX7TV8O+SuGI4CFJA6u4U66GexW/JSd6nEPB+WK7/k3iSiWkOJlHR6YACuzADvC5j52MJjKtzVcT9MYCiZXbx7viGcM4vemHDQkZiBAVUFzodzgAe5HJdqdgm/Vtn3IqLxLsGxdzzez4=
